2025-03-20 17:48:18,159 INFO    MainThread:310437 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-20 17:48:18,159 INFO    MainThread:310437 [wandb_setup.py:_flush():67] Configure stats pid to 310437
2025-03-20 17:48:18,159 INFO    MainThread:310437 [wandb_setup.py:_flush():67] Loading settings from /home/inside-tech/.config/wandb/settings
2025-03-20 17:48:18,159 INFO    MainThread:310437 [wandb_setup.py:_flush():67] Loading settings from /home/inside-tech/Desktop/image_segmentation/wandb/settings
2025-03-20 17:48:18,159 INFO    MainThread:310437 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-20 17:48:18,159 INFO    MainThread:310437 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/inside-tech/Desktop/image_segmentation/wandb/run-20250320_174818-rni24yx3/logs/debug.log
2025-03-20 17:48:18,159 INFO    MainThread:310437 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/inside-tech/Desktop/image_segmentation/wandb/run-20250320_174818-rni24yx3/logs/debug-internal.log
2025-03-20 17:48:18,159 INFO    MainThread:310437 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x70bbe0ce1d00>
2025-03-20 17:48:18,160 INFO    MainThread:310437 [wandb_init.py:init():761] calling init triggers
2025-03-20 17:48:18,160 INFO    MainThread:310437 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-20 17:48:18,160 INFO    MainThread:310437 [wandb_init.py:init():784] starting backend
2025-03-20 17:48:18,160 INFO    MainThread:310437 [wandb_init.py:init():788] sending inform_init request
2025-03-20 17:48:18,161 INFO    MainThread:310437 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-20 17:48:18,161 INFO    MainThread:310437 [wandb_init.py:init():798] backend started and connected
2025-03-20 17:48:18,162 INFO    MainThread:310437 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-20 17:48:18,162 INFO    MainThread:310437 [wandb_init.py:init():891] updated telemetry
2025-03-20 17:48:18,162 INFO    MainThread:310437 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-20 17:48:18,533 INFO    MainThread:310437 [wandb_init.py:init():990] starting run threads in backend
2025-03-20 17:48:18,595 INFO    MainThread:310437 [wandb_run.py:_console_start():2375] atexit reg
2025-03-20 17:48:18,595 INFO    MainThread:310437 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-20 17:48:18,595 INFO    MainThread:310437 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-20 17:48:18,595 INFO    MainThread:310437 [wandb_run.py:_redirect():2315] Redirects installed.
2025-03-20 17:48:18,596 INFO    MainThread:310437 [wandb_init.py:init():1032] run started, returning control to user process
2025-03-20 17:49:30,070 INFO    MainThread:310437 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-20 17:49:30,070 INFO    MainThread:310437 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-20 17:49:30,074 INFO    MainThread:310437 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-20 17:49:30,080 INFO    MainThread:310437 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-20 17:49:30,080 INFO    MainThread:310437 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-20 17:49:30,083 INFO    MainThread:310437 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-20 17:49:30,089 INFO    MainThread:310437 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-20 17:49:30,089 INFO    MainThread:310437 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-20 17:49:30,093 INFO    MainThread:310437 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-20 17:49:31,684 INFO    MainThread:310437 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-20 17:49:31,684 INFO    MainThread:310437 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-20 17:49:31,688 INFO    MainThread:310437 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-20 17:49:31,689 INFO    MainThread:310437 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-20 17:49:31,689 INFO    MainThread:310437 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-20 17:49:31,692 INFO    MainThread:310437 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-20 17:50:26,153 WARNING MsgRouterThr:310437 [router.py:message_loop():63] message_loop has been closed
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-20 17:50:26,161 INFO    MsgRouterThr:310437 [mailbox.py:close():129] Closing mailbox, abandoning 3 handles.
