2025-03-21 15:51:00,850 INFO    MainThread:377668 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/inside-tech/Desktop/image_segmentation/wandb/run-20250321_155100-jld0hlay/logs/debug.log
2025-03-21 15:51:00,850 INFO    MainThread:377668 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/inside-tech/Desktop/image_segmentation/wandb/run-20250321_155100-jld0hlay/logs/debug-internal.log
2025-03-21 15:51:00,850 INFO    MainThread:377668 [wandb_init.py:init():761] calling init triggers
2025-03-21 15:51:00,850 INFO    MainThread:377668 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-21 15:51:00,850 INFO    MainThread:377668 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-21 15:51:00,852 ERROR   MainThread:377668 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-21 15:51:00,853 ERROR   MainThread:377668 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-21 15:51:00,854 ERROR   MainThread:377668 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-21 15:51:00,855 ERROR   MainThread:377668 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-21 15:51:13,656 INFO    MainThread:377668 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-21 15:51:13,656 INFO    MainThread:377668 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-21 15:51:13,657 ERROR   MainThread:377668 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-21 15:51:13,657 ERROR   MainThread:377668 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
