2025-03-22 17:58:15,621 INFO    MainThread:479321 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/inside-tech/Desktop/image_segmentation/wandb/run-20250322_175815-nnuu1rbs/logs/debug.log
2025-03-22 17:58:15,621 INFO    MainThread:479321 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/inside-tech/Desktop/image_segmentation/wandb/run-20250322_175815-nnuu1rbs/logs/debug-internal.log
2025-03-22 17:58:15,621 INFO    MainThread:479321 [wandb_init.py:init():761] calling init triggers
2025-03-22 17:58:15,621 INFO    MainThread:479321 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-22 17:58:15,621 INFO    MainThread:479321 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-22 18:01:38,243 WARNING MsgRouterThr:479321 [router.py:message_loop():63] message_loop has been closed
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-22 18:01:38,244 INFO    MsgRouterThr:479321 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-03-22 18:01:38,272 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/tqdm/std.py", line 1182, in __iter__
    yield obj
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:01:38,279 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/tqdm/std.py", line 1182, in __iter__
    yield obj
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:01:38,494 INFO    MainThread:479321 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-22 18:01:38,494 INFO    MainThread:479321 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-22 18:01:38,494 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:01:38,497 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:01:47,253 INFO    MainThread:479321 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-22 18:01:47,253 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:01:47,255 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:01:47,311 INFO    MainThread:479321 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-22 18:01:47,311 INFO    MainThread:479321 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-22 18:01:47,311 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:01:47,312 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:01:58,140 INFO    MainThread:479321 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-22 18:01:58,140 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:01:58,141 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:01:58,188 INFO    MainThread:479321 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-22 18:01:58,188 INFO    MainThread:479321 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-22 18:01:58,188 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:01:58,189 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:02:04,630 INFO    MainThread:479321 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-22 18:02:04,630 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:02:04,632 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:02:04,679 INFO    MainThread:479321 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-22 18:02:04,679 INFO    MainThread:479321 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-22 18:02:04,679 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:02:04,681 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:02:08,259 INFO    MainThread:479321 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-22 18:02:08,259 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:02:08,264 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:02:08,333 INFO    MainThread:479321 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-22 18:02:08,333 INFO    MainThread:479321 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-22 18:02:08,334 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:02:08,334 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:02:20,854 INFO    MainThread:479321 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-22 18:02:20,855 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:02:20,855 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:02:20,920 INFO    MainThread:479321 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-22 18:02:20,920 INFO    MainThread:479321 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-22 18:02:20,920 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:02:20,921 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:02:33,039 INFO    MainThread:479321 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-22 18:02:33,040 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:02:33,041 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:02:33,102 INFO    MainThread:479321 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-22 18:02:33,102 INFO    MainThread:479321 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-22 18:02:33,102 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:02:33,103 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:03:51,596 INFO    MainThread:479321 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-22 18:03:51,597 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:03:51,599 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:03:51,658 INFO    MainThread:479321 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-22 18:03:51,658 INFO    MainThread:479321 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-22 18:03:51,658 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-22 18:03:51,659 ERROR   MainThread:479321 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
