2025-03-23 10:30:54,627 INFO    MainThread:524596 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-23 10:30:54,627 INFO    MainThread:524596 [wandb_setup.py:_flush():67] Configure stats pid to 524596
2025-03-23 10:30:54,627 INFO    MainThread:524596 [wandb_setup.py:_flush():67] Loading settings from /home/inside-tech/.config/wandb/settings
2025-03-23 10:30:54,627 INFO    MainThread:524596 [wandb_setup.py:_flush():67] Loading settings from /home/inside-tech/Desktop/image_segmentation/wandb/settings
2025-03-23 10:30:54,627 INFO    MainThread:524596 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-23 10:30:54,627 INFO    MainThread:524596 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/inside-tech/Desktop/image_segmentation/wandb/run-20250323_103054-f640dqui/logs/debug.log
2025-03-23 10:30:54,627 INFO    MainThread:524596 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/inside-tech/Desktop/image_segmentation/wandb/run-20250323_103054-f640dqui/logs/debug-internal.log
2025-03-23 10:30:54,627 INFO    MainThread:524596 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7ee960412180>
2025-03-23 10:30:54,627 INFO    MainThread:524596 [wandb_init.py:init():761] calling init triggers
2025-03-23 10:30:54,627 INFO    MainThread:524596 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-23 10:30:54,627 INFO    MainThread:524596 [wandb_init.py:init():784] starting backend
2025-03-23 10:30:54,627 INFO    MainThread:524596 [wandb_init.py:init():788] sending inform_init request
2025-03-23 10:30:54,628 INFO    MainThread:524596 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-23 10:30:54,628 INFO    MainThread:524596 [wandb_init.py:init():798] backend started and connected
2025-03-23 10:30:54,629 INFO    MainThread:524596 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-23 10:30:54,629 INFO    MainThread:524596 [wandb_init.py:init():891] updated telemetry
2025-03-23 10:30:54,631 INFO    MainThread:524596 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-23 10:30:55,041 INFO    MainThread:524596 [wandb_init.py:init():990] starting run threads in backend
2025-03-23 10:30:55,110 INFO    MainThread:524596 [wandb_run.py:_console_start():2375] atexit reg
2025-03-23 10:30:55,110 INFO    MainThread:524596 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-23 10:30:55,110 INFO    MainThread:524596 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-23 10:30:55,110 INFO    MainThread:524596 [wandb_run.py:_redirect():2315] Redirects installed.
2025-03-23 10:30:55,111 INFO    MainThread:524596 [wandb_init.py:init():1032] run started, returning control to user process
2025-03-23 10:31:15,792 INFO    MainThread:524596 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-23 10:31:15,792 INFO    MainThread:524596 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-23 10:31:15,796 INFO    MainThread:524596 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-23 10:31:16,619 INFO    MainThread:524596 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/inside-tech/Desktop/image_segmentation/wandb/run-20250323_103116-2heue2kd/logs/debug.log
2025-03-23 10:31:16,619 INFO    MainThread:524596 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/inside-tech/Desktop/image_segmentation/wandb/run-20250323_103116-2heue2kd/logs/debug-internal.log
2025-03-23 10:31:16,619 INFO    MainThread:524596 [wandb_init.py:init():761] calling init triggers
2025-03-23 10:31:16,619 INFO    MainThread:524596 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'model': 'DeepLabV3_MobileNetV2', 'learning_rate': 0.0001, 'epochs': 100, 'batch_size': 8, 'weight_decay': 0.0001, 'optimizer': 'AdamW', 'scheduler': 'ReduceLROnPlateau', 'experiment_name': 'DeepLabV3_20250323_1031', '_wandb': {}}
2025-03-23 10:31:16,619 INFO    MainThread:524596 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-23 10:31:16,620 INFO    MainThread:524596 [wandb_watch.py:_watch():71] Watching
2025-03-23 10:38:58,290 WARNING MsgRouterThr:524596 [router.py:message_loop():63] message_loop has been closed
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-23 10:38:58,291 INFO    MsgRouterThr:524596 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-03-23 10:38:58,343 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/tqdm/std.py", line 1182, in __iter__
    yield obj
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:38:58,345 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/tqdm/std.py", line 1182, in __iter__
    yield obj
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:38:58,710 INFO    MainThread:524596 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-23 10:38:58,710 INFO    MainThread:524596 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-23 10:38:58,711 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:38:58,712 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:05,428 INFO    MainThread:524596 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-23 10:39:05,429 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:05,430 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:05,492 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:05,493 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:05,493 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:05,493 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:05,494 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:05,494 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:05,495 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:05,495 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:05,496 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:05,496 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:05,496 INFO    MainThread:524596 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-23 10:39:05,496 INFO    MainThread:524596 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-23 10:39:05,497 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:05,497 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:27,269 INFO    MainThread:524596 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-23 10:39:27,270 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:27,271 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:27,323 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:27,324 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:27,324 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:27,325 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:27,325 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:27,326 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:27,326 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:27,326 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:27,327 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:27,327 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:27,327 INFO    MainThread:524596 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-23 10:39:27,328 INFO    MainThread:524596 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-23 10:39:27,328 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-23 10:39:27,328 ERROR   MainThread:524596 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/inside-tech/Desktop/image_segmentation/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
